---
title: "Frequency table by reactivity - Questionnaires"
author: "Mun-Gwan Hong"
date: "05/05/2020"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(table1)

rm(list = ls())
```

```{r filenames}
###  File names

fn <- list(
  i = list(                               #  input
    c19 = '../data/dbs_covid19.v1.RData',
    qn = '../data/questionnaire.v1.RData'
  )
)

#  Check all exists
stopifnot(all(file.exists(c('.', unlist(fn$i)))), 
          all(file.exists(dirname(c('.', unlist(fn$o))))))
```


```{r load}
load(fn$i$c19)
```


```{r reactive}
# log-transformation
mfi <- log(mfi)

#  Confirm sample IDs alignment
stopifnot(identical(rownames(mfi), sinfo$id))

#  dummy binder IDs to minimize any errors
colnames(mfi) <- binder$id <- paste0("b", seq(1, ncol(mfi)))

##  Limit to 'IgG - CoV_Spike-foldon`
binder <- binder %>% 
  filter(detect_Ab == "IgG" & grepl("CoV_Spike", Binder))
mfi <- mfi[, colnames(mfi) %in% binder$id]
stopifnot(identical(colnames(mfi), binder$id))

#  combine sample info and MFI
mfi_pn <- mfi %>% 
  as_tibble() %>% 
  bind_cols(sinfo, .) %>% 
  filter(grepl("CBC\\+01", id)) %>%    # CBC+01 only
  filter(Nr_OK_spots > 0) %>%            # OK blood spot
  select_at(c("id", binder$id))                # binder data only


###  Based on peak value

den <- mfi_pn %>% 
  select_if(is.numeric) %>% 
  lapply(density)

#  peak
m <- sapply(den, function(x) x$x[which.max(x$y)])
#  std.dev. of 80% around the peak
s <- sapply(names(m), function(ii) {
  df <- abs(mfi_pn[[ii]] - m[ii])
  qtl <- quantile(df, probs = c(0.8))
  sd(mfi_pn[[ii]][df <= qtl])
})

cutoff <- m + 6 * s


pos_neg <- mfi_pn %>% 
  pivot_longer(-id, names_to = "binder") %>% 
  mutate(pn = value >= cutoff[binder]) %>% 
  group_by(id) %>% 
  summarise(Reactive = if_else(all(pn), "Yes", "No"))

tg <- inner_join(sinfo, pos_neg, by= "id") %>% 
  select(id, Sex:Reactive) 

# samples without OK spot
tmp <- sinfo %>% 
  filter(grepl("CBC\\+01", id)) %>% 
  filter(Nr_OK_spots == 0)
```

There were `r nrow(tmp)` samples without any good blood spot.

```{r pvalue_column}

tg <- tg %>% 
  mutate(Reactive = factor(Reactive, levels = c("Yes", "No", "P-value")))

rndr <- function(x, name, ...) {
  if (length(x) == 0) {
    y <- tg[[name]]
    s <- rep("", length(render.default(x=y, name=name, ...)))
    p <- fisher.test(table(y, droplevels(tg$Reactive), useNA = "no"))$p.value
    
    s[2] <- sub("<", "&lt;", format.pval(p, digits=3, eps=0.001))
    s
  } else {
    render.default(x=x, name=name, ...)
  }
}
rndr.strat <- function(label, n, ...) {
    ifelse(n==0, label, render.strat.default(label, n, ...))
}
```


###  Symptom

```{r}
label(tg$Symptom) <- "Flu-like symptom"
table1(~ Symptom | Reactive, tg, droplevels=F, render= rndr, render.strat=rndr.strat, overall=F)
```


###  Sex, Age group and Breath

```{r}
label(tg$Age_grp) <- "Age group"
units(tg$Age_grp) <- "years"
label(tg$Breath) <- "Breathing difficulty"
table1(~ Sex + Age_grp + Breath | Reactive, tg,
       droplevels=F, render= rndr, render.strat=rndr.strat, overall=F)
```

